/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item, ItemClassName, ItemSlotType, ItemTier, Language, TooltipBehavior, TooltipPlacement } from "./types";
export { Item, ItemClassName, ItemSlotType, ItemTier, Language, TooltipBehavior, TooltipPlacement } from "./types";
export namespace Components {
    interface DlItemCard {
        /**
          * Hover effect on the card. `"none"` does nothing, `"scale"` enlarges on hover.
          * @default 'none'
         */
        "hoverEffect": 'none' | 'scale';
        /**
          * Item class name (e.g. `"upgrade_clip_size"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Show the tier badge on hover. When not set, falls back to the global provider value.
         */
        "showTierBadge"?: boolean;
    }
    interface DlItemGrid {
        /**
          * When `true`, only shows items available in the shop.
          * @default true
         */
        "shopableOnly": boolean;
        /**
          * Filter items by slot type: `"weapon"`, `"vitality"`, or `"spirit"`.
         */
        "slotType"?: ItemSlotType;
        /**
          * Filter items by tier (1–4).
         */
        "tier"?: ItemTier;
    }
    interface DlItemTooltip {
        /**
          * Item data to display in the tooltip.
         */
        "itemData"?: Item;
    }
    interface DlProvider {
        /**
          * Language for item data (e.g. `"english"`, `"brazilian"`, `"japanese"`).
          * @default Language.EN
         */
        "language": Language;
        /**
          * Show tier badge on item cards globally. Individual cards can override this.
          * @default true
         */
        "showTierBadge": boolean;
        /**
          * How the item tooltip is triggered: `"tooltip"` on hover, `"popover"` on click, or `"none"` to disable.
          * @default 'tooltip'
         */
        "tooltipBehavior": TooltipBehavior;
        /**
          * Delay in milliseconds before showing the tooltip on hover.
          * @default 150
         */
        "tooltipDelay": number;
        /**
          * Preferred tooltip position. `"auto"` picks the side with the most space.
          * @default 'auto'
         */
        "tooltipPlacement": TooltipPlacement;
    }
    interface DlShopPanel {
        /**
          * The tab to display initially. One of `"weapon"`, `"vitality"`, or `"spirit"`.
          * @default 'weapon'
         */
        "activeTab": ItemSlotType;
        /**
          * Hover effect applied to each item card. One of `"none"` or `"scale"`.
          * @default 'scale'
         */
        "hoverEffect": 'none' | 'scale';
    }
}
declare global {
    interface HTMLDlItemCardElement extends Components.DlItemCard, HTMLStencilElement {
    }
    var HTMLDlItemCardElement: {
        prototype: HTMLDlItemCardElement;
        new (): HTMLDlItemCardElement;
    };
    interface HTMLDlItemGridElement extends Components.DlItemGrid, HTMLStencilElement {
    }
    var HTMLDlItemGridElement: {
        prototype: HTMLDlItemGridElement;
        new (): HTMLDlItemGridElement;
    };
    interface HTMLDlItemTooltipElement extends Components.DlItemTooltip, HTMLStencilElement {
    }
    var HTMLDlItemTooltipElement: {
        prototype: HTMLDlItemTooltipElement;
        new (): HTMLDlItemTooltipElement;
    };
    interface HTMLDlProviderElement extends Components.DlProvider, HTMLStencilElement {
    }
    var HTMLDlProviderElement: {
        prototype: HTMLDlProviderElement;
        new (): HTMLDlProviderElement;
    };
    interface HTMLDlShopPanelElement extends Components.DlShopPanel, HTMLStencilElement {
    }
    var HTMLDlShopPanelElement: {
        prototype: HTMLDlShopPanelElement;
        new (): HTMLDlShopPanelElement;
    };
    interface HTMLElementTagNameMap {
        "dl-item-card": HTMLDlItemCardElement;
        "dl-item-grid": HTMLDlItemGridElement;
        "dl-item-tooltip": HTMLDlItemTooltipElement;
        "dl-provider": HTMLDlProviderElement;
        "dl-shop-panel": HTMLDlShopPanelElement;
    }
}
declare namespace LocalJSX {
    interface DlItemCard {
        /**
          * Hover effect on the card. `"none"` does nothing, `"scale"` enlarges on hover.
          * @default 'none'
         */
        "hoverEffect"?: 'none' | 'scale';
        /**
          * Item class name (e.g. `"upgrade_clip_size"`). Alternative to `item-id`.
         */
        "itemClassName"?: ItemClassName;
        /**
          * Pre-loaded item data object. When provided, skips the API fetch.
         */
        "itemData"?: Item;
        /**
          * Item numeric ID. Alternative to `class-name`.
         */
        "itemId"?: number;
        /**
          * Show the tier badge on hover. When not set, falls back to the global provider value.
         */
        "showTierBadge"?: boolean;
    }
    interface DlItemGrid {
        /**
          * When `true`, only shows items available in the shop.
          * @default true
         */
        "shopableOnly"?: boolean;
        /**
          * Filter items by slot type: `"weapon"`, `"vitality"`, or `"spirit"`.
         */
        "slotType"?: ItemSlotType;
        /**
          * Filter items by tier (1–4).
         */
        "tier"?: ItemTier;
    }
    interface DlItemTooltip {
        /**
          * Item data to display in the tooltip.
         */
        "itemData"?: Item;
    }
    interface DlProvider {
        /**
          * Language for item data (e.g. `"english"`, `"brazilian"`, `"japanese"`).
          * @default Language.EN
         */
        "language"?: Language;
        /**
          * Show tier badge on item cards globally. Individual cards can override this.
          * @default true
         */
        "showTierBadge"?: boolean;
        /**
          * How the item tooltip is triggered: `"tooltip"` on hover, `"popover"` on click, or `"none"` to disable.
          * @default 'tooltip'
         */
        "tooltipBehavior"?: TooltipBehavior;
        /**
          * Delay in milliseconds before showing the tooltip on hover.
          * @default 150
         */
        "tooltipDelay"?: number;
        /**
          * Preferred tooltip position. `"auto"` picks the side with the most space.
          * @default 'auto'
         */
        "tooltipPlacement"?: TooltipPlacement;
    }
    interface DlShopPanel {
        /**
          * The tab to display initially. One of `"weapon"`, `"vitality"`, or `"spirit"`.
          * @default 'weapon'
         */
        "activeTab"?: ItemSlotType;
        /**
          * Hover effect applied to each item card. One of `"none"` or `"scale"`.
          * @default 'scale'
         */
        "hoverEffect"?: 'none' | 'scale';
    }

    interface DlItemCardAttributes {
        "itemId": number;
        "itemClassName": ItemClassName;
        "hoverEffect": 'none' | 'scale';
        "showTierBadge": boolean;
    }
    interface DlItemGridAttributes {
        "slotType": ItemSlotType;
        "tier": ItemTier;
        "shopableOnly": boolean;
    }
    interface DlProviderAttributes {
        "language": Language;
        "tooltipBehavior": TooltipBehavior;
        "tooltipPlacement": TooltipPlacement;
        "tooltipDelay": number;
        "showTierBadge": boolean;
    }
    interface DlShopPanelAttributes {
        "activeTab": ItemSlotType;
        "hoverEffect": 'none' | 'scale';
    }

    interface IntrinsicElements {
        "dl-item-card": Omit<DlItemCard, keyof DlItemCardAttributes> & { [K in keyof DlItemCard & keyof DlItemCardAttributes]?: DlItemCard[K] } & { [K in keyof DlItemCard & keyof DlItemCardAttributes as `attr:${K}`]?: DlItemCardAttributes[K] } & { [K in keyof DlItemCard & keyof DlItemCardAttributes as `prop:${K}`]?: DlItemCard[K] };
        "dl-item-grid": Omit<DlItemGrid, keyof DlItemGridAttributes> & { [K in keyof DlItemGrid & keyof DlItemGridAttributes]?: DlItemGrid[K] } & { [K in keyof DlItemGrid & keyof DlItemGridAttributes as `attr:${K}`]?: DlItemGridAttributes[K] } & { [K in keyof DlItemGrid & keyof DlItemGridAttributes as `prop:${K}`]?: DlItemGrid[K] };
        "dl-item-tooltip": DlItemTooltip;
        "dl-provider": Omit<DlProvider, keyof DlProviderAttributes> & { [K in keyof DlProvider & keyof DlProviderAttributes]?: DlProvider[K] } & { [K in keyof DlProvider & keyof DlProviderAttributes as `attr:${K}`]?: DlProviderAttributes[K] } & { [K in keyof DlProvider & keyof DlProviderAttributes as `prop:${K}`]?: DlProvider[K] };
        "dl-shop-panel": Omit<DlShopPanel, keyof DlShopPanelAttributes> & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes]?: DlShopPanel[K] } & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes as `attr:${K}`]?: DlShopPanelAttributes[K] } & { [K in keyof DlShopPanel & keyof DlShopPanelAttributes as `prop:${K}`]?: DlShopPanel[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dl-item-card": LocalJSX.IntrinsicElements["dl-item-card"] & JSXBase.HTMLAttributes<HTMLDlItemCardElement>;
            "dl-item-grid": LocalJSX.IntrinsicElements["dl-item-grid"] & JSXBase.HTMLAttributes<HTMLDlItemGridElement>;
            "dl-item-tooltip": LocalJSX.IntrinsicElements["dl-item-tooltip"] & JSXBase.HTMLAttributes<HTMLDlItemTooltipElement>;
            "dl-provider": LocalJSX.IntrinsicElements["dl-provider"] & JSXBase.HTMLAttributes<HTMLDlProviderElement>;
            "dl-shop-panel": LocalJSX.IntrinsicElements["dl-shop-panel"] & JSXBase.HTMLAttributes<HTMLDlShopPanelElement>;
        }
    }
}
